AllCops:
  TargetRubyVersion: 3.0.0
  EnabledByDefault: true
  NewCops: enable
  Exclude:
    - examples/**/*

Style/DocumentationMethod:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Copyright:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoreMacros: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Style/Send:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 30