version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test_three_zero_zero:
    docker:
      - image: circleci/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  test:
    jobs:
      - test_three_zero_zero
